---
- hosts: all
  sudo: yes
  tasks:
  - user:
     name: ansible
     comment: "Ansible"
     uid: 1010
     group: sudo
  - name: Set up multiple authorized keys
    authorized_key:
      user: ansible
      state: present
      key: '{{ item }}'
    with_file:
     - /tmp/ansible
  - lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^ansible ALL='
      line: 'ansible ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'
