---
- hosts: all
  sudo: yes
  tasks:
  - name: Patch
    become: true
    apt:
      update_cache: yes
      upgrade: dist
    register: out
  - name: display
    debug: var=out
  - name: Installing Dependencies
    apt:
      name: "{{item}}"
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common
     - php7.0
     - libapache2-mod-php7.0
    become: yes
  - user:
     name: ansible
     comment: "Ansible"
     uid: 1010
     group: sudo
  - name: Set up multiple authorized keys
    authorized_key:
      user: ansible
      state: present
      key: '{{ item }}'
    with_file:
     - /tmp/ansible
  - lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^ansible ALL='
      line: 'ansible ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'
  - name: apticron | install debian ntp
    apt: pkg=apticron state=present
  - name: apticron | configure
    template: src=/tmp/apticron.conf dest=/etc/apticron/apticron.conf owner=root group=root mode=0644 backup=yes
